/analyze can't HANDLE the truth!
Error 1 error C2220: warning treated as error - no 'object' file
generated sqlite3.h 4432
Warning 2 warning C4091: '__declspec' : ignored on left of 'int' when no
variable is declared sqlite3.h 4432
Error 3 error C2143: syntax error : missing ';' before '__assume'
sqlite3.h 4432
Error 4 error C2059: syntax error : '__assume' sqlite3.h 4432